Hi, 

Below is a daily table for an active acount at Shopify (an online ecommerce, retail platform). The table is called store_account and the columns are:
    


| Column Name | Data Type | Description |
---|---|---
| store_id | integer | a unique Shopify store id |
| date | string | date |
| status | string | Possible values are: [‘open’, 'closed’, ‘fraud’] |
| revenue | double | Amount of spend in USD |



Here's some additional information about the table:
* The granularity of the table is store_id and day
* Assume “closed” and “fraud” are permanent labels
* Active = daily revenue > 0 
* Accounts get labeled by Shopify as fraudulent and they no longer can sell product   
* Every day of the table has every store_id that has ever used Shopify

    

Given the above, write code using Python (Pandas library) to show what percent of active stores were fraudulent by day. 
    
Some clarifications:
* We want one value for each day in the month.
* A store can be fraudulent and active on same day. E.g. they could generate revenue until 10AM, then be flagged as fradulent from 10AM onward.

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("./datasets/fraud_data.csv")
df.head()

   store_id        date  status  revenue
0         1  2023-06-01    open    50.00
1         2  2023-06-01  closed     0.00
2         3  2023-06-01    open   120.50
3         4  2023-06-01    open    80.25
4         5  2023-06-01    open    30.00

In [5]:
df

    store_id        date  status  revenue
0          1  2023-06-01    open    50.00
1          2  2023-06-01  closed     0.00
2          3  2023-06-01    open   120.50
3          4  2023-06-01    open    80.25
4          5  2023-06-01    open    30.00
5          6  2023-06-01    open    75.80
6          7  2023-06-01    open    40.00
7          1  2023-06-02    open    60.00
8          2  2023-06-02  closed     0.00
9          3  2023-06-02    open    80.25
10         4  2023-06-02    open     0.00
11         4  2023-06-02   fraud     0.00
12         5  2023-06-02    open    45.60
13         6  2023-06-02    open    90.10
14         7  2023-06-02    open    55.00
15         1  2023-06-03    open    70.00
16         2  2023-06-03  closed     0.00
17         3  2023-06-03   fraud     0.00
18         3  2023-06-03    open   100.75
19         4  2023-06-03    open    60.00
20         5  2023-06-03    open   110.30
21         6  2023-06-03    open    70.00
22         1  2023-06-04   fraud     0.00
23         2  2023-06-04  closed     0.00
24         3  2023-06-04    open    60.40
25         4  2023-06-04    open     0.00
26         4  2023-06-04   fraud     0.00
27         5  2023-06-04  closed     0.00
28         6  2023-06-04    open   130.20
29         7  2023-06-04    open    85.00
30         1  2023-06-05  closed     0.00
31         1  2023-06-05   fraud     0.00
32         2  2023-06-05  closed     0.00
33         3  2023-06-05   fraud     0.00
34         4  2023-06-05    open   120.75
35         5  2023-06-05  closed     0.00
36         6  2023-06-05    open   130.20
37         7  2023-06-05    open    85.00

In [9]:
df.groupby("date").apply(lambda x:x.status.eq("fraud").sum()/x.status.count()*100)

date
2023-06-01     0.000000
2023-06-02    12.500000
2023-06-03    14.285714
2023-06-04    25.000000
2023-06-05    25.000000
dtype: float64